/**
 * Generator for tree-shakable service functions.
 *
 * This module generates standalone functions that can be tree-shaken.
 * Each entity service is a module of standalone functions that use
 * the tree-shakable OData functions directly.
 *
 * @since 1.0.0
 */
import type { DataModel, EntityTypeModel, EntitySetModel } from "../model/DataModel.js"
import type { ODataVersion } from "../parser/EdmxSchema.js"
import {
  getServiceClassName,
  getIdTypeName,
  getEditableTypeName
} from "./NamingHelper.js"

/**
 * Version-specific imports and identifiers.
 */
interface VersionConfig {
  readonly odataNamespace: string
  readonly buildEntityPath: string
  readonly queryOptionsType: string
  readonly clientConfigTag: string
}

const V2_CONFIG: VersionConfig = {
  odataNamespace: "OData",
  buildEntityPath: "buildEntityPath",
  queryOptionsType: "ODataQueryOptions",
  clientConfigTag: "ODataClientConfig"
}

const V4_CONFIG: VersionConfig = {
  odataNamespace: "ODataV4",
  buildEntityPath: "buildEntityPathV4",
  queryOptionsType: "ODataV4QueryOptions",
  clientConfigTag: "ODataV4ClientConfig"
}

const getVersionConfig = (version: ODataVersion): VersionConfig =>
  version === "V4" ? V4_CONFIG : V2_CONFIG

/**
 * Generated service function file.
 *
 * @since 1.0.0
 * @category types
 */
export interface GeneratedServiceFnFile {
  readonly fileName: string
  readonly content: string
}

/**
 * Result of service function generation.
 *
 * @since 1.0.0
 * @category types
 */
export interface ServiceFnGenerationResult {
  readonly entityServices: ReadonlyArray<GeneratedServiceFnFile>
}

/**
 * Generate all tree-shakable service function files.
 *
 * @since 1.0.0
 * @category generation
 */
export const generateServiceFns = (dataModel: DataModel): ServiceFnGenerationResult => {
  const entityServices: GeneratedServiceFnFile[] = []

  // Generate individual entity service files
  for (const entitySet of dataModel.entitySets.values()) {
    const entityType = dataModel.entityTypes.get(entitySet.entityTypeFqName)
    if (entityType) {
      const serviceClassName = getServiceClassName(entitySet.name)
      entityServices.push({
        fileName: `${serviceClassName}.ts`,
        content: generateEntityServiceFnFile(entitySet, entityType, dataModel)
      })
    }
  }

  return { entityServices }
}

/**
 * Generate a single entity service function file.
 */
const generateEntityServiceFnFile = (
  entitySet: EntitySetModel,
  entityType: EntityTypeModel,
  dataModel: DataModel
): string => {
  const lines: string[] = []
  const versionConfig = getVersionConfig(dataModel.version)
  const serviceClassName = getServiceClassName(entitySet.name)
  const entityName = entityType.name
  const idTypeName = getIdTypeName(entityName)
  const editableName = getEditableTypeName(entityName)
  const hasKeys = entityType.keys.length > 0
  const isV4 = dataModel.version === "V4"

  // Header and imports
  lines.push(`/**`)
  lines.push(` * Tree-shakable ${entityName} service functions for ${dataModel.serviceName} OData ${dataModel.version}.`)
  lines.push(` * Generated by odata-effect-gen.`)
  lines.push(` *`)
  lines.push(` * @example`)
  lines.push(` * \`\`\`ts`)
  lines.push(` * // Namespace import - nice autocomplete, tree-shakable`)
  lines.push(` * import { ${serviceClassName} } from "@template/${dataModel.serviceName.toLowerCase()}-effect"`)
  lines.push(` * const items = yield* ${serviceClassName}.getAll()`)
  lines.push(` *`)
  lines.push(` * // Direct import - maximum tree-shaking`)
  lines.push(` * import { getAll } from "@template/${dataModel.serviceName.toLowerCase()}-effect/${serviceClassName}"`)
  lines.push(` * const items = yield* getAll()`)
  lines.push(` * \`\`\``)
  lines.push(` *`)
  lines.push(` * @since 1.0.0`)
  lines.push(` */`)
  lines.push(`import type * as Effect from "effect/Effect"`)
  lines.push(`import * as Schema from "effect/Schema"`)
  lines.push(`import type { HttpClient } from "@effect/platform"`)
  lines.push(`import type * as HttpClientError from "@effect/platform/HttpClientError"`)
  lines.push(`import type * as HttpBody from "@effect/platform/HttpBody"`)
  lines.push(``)

  // Import models
  lines.push(`import {`)
  lines.push(`  ${entityName},`)
  if (hasKeys) {
    lines.push(`  type ${idTypeName},`)
  }
  lines.push(`  ${editableName}`)
  lines.push(`} from "./Models.js"`)
  lines.push(``)

  // Import OData infrastructure (version-specific)
  lines.push(`import {`)
  lines.push(`  ${versionConfig.odataNamespace},`)
  lines.push(`  ${versionConfig.buildEntityPath},`)
  lines.push(`  ${versionConfig.clientConfigTag},`)
  lines.push(`  type ${versionConfig.queryOptionsType},`)
  if (!isV4) {
    lines.push(`  type SapError,`)
  }
  lines.push(`  type ODataError,`)
  lines.push(`  type ParseError`)
  lines.push(`} from "@odata-effect/odata-effect"`)
  lines.push(``)

  // Service error type
  lines.push(`// ============================================================================`)
  lines.push(`// Types`)
  lines.push(`// ============================================================================`)
  lines.push(``)
  lines.push(`/**`)
  lines.push(` * Error type for ${entityName} service operations.`)
  lines.push(` *`)
  lines.push(` * @since 1.0.0`)
  lines.push(` * @category errors`)
  lines.push(` */`)
  lines.push(`export type ${serviceClassName}Error =`)
  lines.push(`  | HttpClientError.HttpClientError`)
  lines.push(`  | HttpBody.HttpBodyError`)
  lines.push(`  | ParseError`)
  if (!isV4) {
    lines.push(`  | SapError`)
  }
  lines.push(`  | ODataError`)
  lines.push(``)

  // Dependencies type
  lines.push(`/**`)
  lines.push(` * Dependencies required for ${entityName} service operations.`)
  lines.push(` *`)
  lines.push(` * @since 1.0.0`)
  lines.push(` * @category context`)
  lines.push(` */`)
  lines.push(`export type ${serviceClassName}Context = ${versionConfig.clientConfigTag} | HttpClient.HttpClient`)
  lines.push(``)

  // ID normalizer (if entity has keys)
  if (hasKeys) {
    lines.push(`// ============================================================================`)
    lines.push(`// Internal Helpers`)
    lines.push(`// ============================================================================`)
    lines.push(``)
    const normalizeIdFn = `normalizeId`
    lines.push(`const ${normalizeIdFn} = (id: ${idTypeName}): string =>`)

    if (entityType.keys.length === 1) {
      const keyProp = entityType.keys[0]
      const keyTsType = keyProp.typeMapping.tsType
      const primitiveCheck = keyTsType === "number" ? "number" : "string"
      lines.push(`  typeof id === "${primitiveCheck}" ? String(id) : String(id.${keyProp.name})`)
    } else {
      const keyParts = entityType.keys.map((k) => `${k.odataName}='\${String(id.${k.name})}'`).join(",")
      lines.push(`  typeof id === "string" ? id : \`${keyParts}\``)
    }
    lines.push(``)
  }

  // Standalone functions
  lines.push(`// ============================================================================`)
  lines.push(`// Standalone Tree-Shakable Functions`)
  lines.push(`// ============================================================================`)
  lines.push(``)

  // getAll
  lines.push(`/**`)
  lines.push(` * Fetch all ${entityName} entities.`)
  lines.push(` *`)
  lines.push(` * @since 1.0.0`)
  lines.push(` * @category operations`)
  lines.push(` */`)
  lines.push(`export const getAll = (`)
  lines.push(`  options?: ${versionConfig.queryOptionsType}`)
  lines.push(`): Effect.Effect<`)
  lines.push(`  ReadonlyArray<${entityName}>,`)
  lines.push(`  ${serviceClassName}Error,`)
  lines.push(`  ${serviceClassName}Context`)
  lines.push(`> =>`)
  lines.push(`  ${versionConfig.odataNamespace}.getCollection("${entitySet.name}", ${entityName}, options)`)
  lines.push(``)

  // getById (if entity has keys)
  if (hasKeys) {
    const keyObj = entityType.keys.length === 1
      ? `{ ${entityType.keys[0].odataName}: normalizeId(id) }`
      : `normalizeId(id)`

    lines.push(`/**`)
    lines.push(` * Fetch a single ${entityName} by ID.`)
    lines.push(` *`)
    lines.push(` * @since 1.0.0`)
    lines.push(` * @category operations`)
    lines.push(` */`)
    lines.push(`export const getById = (`)
    lines.push(`  id: ${idTypeName}`)
    lines.push(`): Effect.Effect<`)
    lines.push(`  ${entityName},`)
    lines.push(`  ${serviceClassName}Error,`)
    lines.push(`  ${serviceClassName}Context`)
    lines.push(`> =>`)
    lines.push(`  ${versionConfig.odataNamespace}.get(`)
    lines.push(`    ${versionConfig.buildEntityPath}("${entitySet.name}", ${keyObj}),`)
    lines.push(`    ${entityName}`)
    lines.push(`  )`)
    lines.push(``)
  }

  // create
  lines.push(`/**`)
  lines.push(` * Create a new ${entityName} entity.`)
  lines.push(` *`)
  lines.push(` * @since 1.0.0`)
  lines.push(` * @category operations`)
  lines.push(` */`)
  lines.push(`export const create = (`)
  lines.push(`  entity: ${editableName}`)
  lines.push(`): Effect.Effect<`)
  lines.push(`  ${entityName},`)
  lines.push(`  ${serviceClassName}Error,`)
  lines.push(`  ${serviceClassName}Context`)
  lines.push(`> =>`)
  lines.push(`  ${versionConfig.odataNamespace}.post("${entitySet.name}", entity, ${editableName}, ${entityName})`)
  lines.push(``)

  // update (if entity has keys)
  if (hasKeys) {
    const keyObj = entityType.keys.length === 1
      ? `{ ${entityType.keys[0].odataName}: normalizeId(id) }`
      : `normalizeId(id)`

    lines.push(`/**`)
    lines.push(` * Update an existing ${entityName} entity.`)
    lines.push(` *`)
    lines.push(` * @since 1.0.0`)
    lines.push(` * @category operations`)
    lines.push(` */`)
    lines.push(`export const update = (`)
    lines.push(`  id: ${idTypeName},`)
    lines.push(`  entity: Partial<${editableName}>`)
    lines.push(`): Effect.Effect<`)
    lines.push(`  void,`)
    lines.push(`  ${serviceClassName}Error,`)
    lines.push(`  ${serviceClassName}Context`)
    lines.push(`> =>`)
    lines.push(`  ${versionConfig.odataNamespace}.patch(`)
    lines.push(`    ${versionConfig.buildEntityPath}("${entitySet.name}", ${keyObj}),`)
    lines.push(`    entity,`)
    lines.push(`    Schema.partial(${editableName})`)
    lines.push(`  )`)
    lines.push(``)

    // delete
    lines.push(`/**`)
    lines.push(` * Delete a ${entityName} entity.`)
    lines.push(` *`)
    lines.push(` * @since 1.0.0`)
    lines.push(` * @category operations`)
    lines.push(` */`)
    lines.push(`export const del = (`)
    lines.push(`  id: ${idTypeName}`)
    lines.push(`): Effect.Effect<`)
    lines.push(`  void,`)
    lines.push(`  ${serviceClassName}Error,`)
    lines.push(`  ${serviceClassName}Context`)
    lines.push(`> =>`)
    lines.push(`  ${versionConfig.odataNamespace}.del(`)
    lines.push(`    ${versionConfig.buildEntityPath}("${entitySet.name}", ${keyObj})`)
    lines.push(`  )`)
    lines.push(``)

    // Alias for nice naming
    lines.push(`// Alias for nice naming`)
    lines.push(`export { del as delete }`)
    lines.push(``)
  }

  return lines.join("\n")
}
