/**
 * Generator for entity services using the crud factory.
 *
 * This module generates a single Services.ts file that creates CRUD services
 * for all entity sets using the crud factory from @odata-effect/odata-effect.
 *
 * @since 1.0.0
 */
import type { DataModel, EntitySetModel, EntityTypeModel } from "../model/DataModel.js"
import type { ODataVersion } from "../parser/EdmxSchema.js"
import {
  formatRelativeImport,
  getEditableTypeName,
  getIdTypeName,
  getPartialEditableTypeName,
  getServiceClassName
} from "./NamingHelper.js"

/**
 * Generated service file.
 *
 * @since 1.0.0
 * @category types
 */
export interface GeneratedServiceFile {
  readonly fileName: string
  readonly content: string
}

/**
 * Result of service generation.
 *
 * @since 1.0.0
 * @category types
 */
export interface ServiceGenerationResult {
  readonly servicesFile: GeneratedServiceFile
}

/**
 * Options for service generation.
 *
 * @since 1.0.0
 * @category types
 */
export interface ServiceGeneratorOptions {
  /**
   * Add .js extensions to relative imports for ESM compatibility.
   */
  readonly esmExtensions: boolean
}

/**
 * Generate the Services.ts file using crud factory.
 *
 * @since 1.0.0
 * @category generation
 */
export const generateServiceFns = (
  dataModel: DataModel,
  options: ServiceGeneratorOptions
): ServiceGenerationResult => {
  const content = generateServicesFile(dataModel, options.esmExtensions)
  return {
    servicesFile: {
      fileName: "Services.ts",
      content
    }
  }
}

/**
 * Generate the Services.ts file content.
 */
const generateServicesFile = (dataModel: DataModel, esmExtensions: boolean): string => {
  const lines: Array<string> = []
  const isV4 = dataModel.version === "V4"
  const crudImportPath = isV4
    ? "@odata-effect/odata-effect/CrudV4"
    : "@odata-effect/odata-effect/Crud"

  // Collect all entity sets with their types
  const entitySets: Array<{
    entitySet: EntitySetModel
    entityType: EntityTypeModel
  }> = []

  for (const entitySet of dataModel.entitySets.values()) {
    const entityType = dataModel.entityTypes.get(entitySet.entityTypeFqName)
    if (entityType) {
      entitySets.push({ entitySet, entityType })
    }
  }

  // Header
  lines.push(`/**`)
  lines.push(` * Entity services for ${dataModel.serviceName} OData ${dataModel.version}.`)
  lines.push(` * Generated by odata-effect-gen.`)
  lines.push(` *`)
  lines.push(` * Uses the crud factory for minimal generated code.`)
  lines.push(` *`)
  lines.push(` * @since 1.0.0`)
  lines.push(` */`)
  lines.push(`import { crud, readCollection, readOne } from "${crudImportPath}"`)
  const clientModule = isV4 ? "ODataV4" : "OData"
  const queryOptions = isV4 ? "ODataV4QueryOptions" : "ODataQueryOptions"
  const buildPath = isV4 ? "buildEntityPathV4" : "buildEntityPath"
  lines.push(`import type * as Schema from "effect/Schema"`)
  lines.push(`import * as Client from "@odata-effect/odata-effect/${clientModule}"`)
  lines.push(``)

  // Import all entity types
  const modelImports: Array<string> = []
  for (const { entityType } of entitySets) {
    modelImports.push(entityType.name, `Create${entityType.name}`)
    if (entityType.keys.length > 0) {
      modelImports.push(`type ${getIdTypeName(entityType.name)}`)
    }
    modelImports.push(getEditableTypeName(entityType.name))
    modelImports.push(getPartialEditableTypeName(entityType.name))
  }

  lines.push(`import {`)
  for (let i = 0; i < modelImports.length; i++) {
    const isLast = i === modelImports.length - 1
    lines.push(`  ${modelImports[i]}${isLast ? "" : ","}`)
  }
  lines.push(`} from "${formatRelativeImport("Models", esmExtensions)}"`)
  lines.push(``)

  // Re-export types from the crud module
  lines.push(`// Re-export types for convenience`)
  lines.push(`export type { CrudError, CrudContext, CrudService } from "${crudImportPath}"`)
  lines.push(``)

  // Generate each service
  lines.push(`// ============================================================================`)
  lines.push(`// Entity Services`)
  lines.push(`// ============================================================================`)
  lines.push(``)

  for (const { entitySet, entityType } of entitySets) {
    const serviceClassName = getServiceClassName(entitySet.name)
    const entityName = entityType.name
    const editableName = getEditableTypeName(entityName)
    const partialEditableName = getPartialEditableTypeName(entityName)
    const hasKeys = entityType.keys.length > 0

    lines.push(`/**`)
    lines.push(` * CRUD service for ${entityName} entities.`)
    lines.push(` *`)
    lines.push(` * @since 1.0.0`)
    lines.push(` * @category services`)
    lines.push(` */`)

    if (hasKeys) {
      lines.push(`export const ${serviceClassName} = /*#__PURE__*/ crud({`)
      lines.push(`  path: "${entitySet.name}",`)
      lines.push(`  schema: ${entityName},`)
      lines.push(`  editableSchema: ${editableName},`)
      lines.push(`  createSchema: Create${entityName},`)
      lines.push(`  partialEditableSchema: ${partialEditableName},`)
      lines.push(`  idToKey: ${generateIdToKeyFunction(entityType, dataModel.version)}`)
      lines.push(`})`)
    } else {
      // Entity without keys - can only getAll and create
      lines.push(`export const ${serviceClassName} = /*#__PURE__*/ crud({`)
      lines.push(`  path: "${entitySet.name}",`)
      lines.push(`  schema: ${entityName},`)
      lines.push(`  editableSchema: ${editableName},`)
      lines.push(`  createSchema: Create${entityName},`)
      lines.push(`  partialEditableSchema: ${partialEditableName},`)
      lines.push(`  idToKey: (_id: never) => { throw new Error("Entity has no keys") }`)
      lines.push(`})`)
    }
    const suffix = serviceClassName.replace(/Service$/, "")
    lines.push(
      `export const getAll${suffix} = (options?: Client.${queryOptions}) => readCollection("${entitySet.name}", ${entityName}, options)`
    )
    lines.push(
      `export const create${suffix} = (entity: Create${entityName}) => Client.post("${entitySet.name}", entity, Create${entityName}, ${entityName})`
    )
    lines.push(
      `export const getAll${suffix}WithSchema = <A, I, R>(schema: Schema.Codec<A, I, R>, options?: Client.${queryOptions}) => Client.getCollection("${entitySet.name}", schema, options)`
    )
    if (hasKeys) {
      const idType = getIdTypeName(entityName)
      lines.push(
        `export const getById${suffix}WithSchema = <A, I, R>(id: ${idType}, schema: Schema.Codec<A, I, R>, options?: Client.${queryOptions}) => Client.get(Client.${buildPath}("${entitySet.name}", key${suffix}(id)), schema, options)`
      )
      lines.push(`const key${suffix} = ${generateIdToKeyFunction(entityType, dataModel.version)}`)
      lines.push(
        `export const getById${suffix} = (id: ${idType}, options?: Client.${queryOptions}) => readOne(Client.${buildPath}("${entitySet.name}", key${suffix}(id)), ${entityName}, options)`
      )
      lines.push(
        `export const update${suffix} = (id: ${idType}, entity: Partial<${editableName}>) => Client.patch(Client.${buildPath}("${entitySet.name}", key${suffix}(id)), entity, ${partialEditableName})`
      )
      lines.push(
        `export const delete${suffix} = (id: ${idType}) => Client.del(Client.${buildPath}("${entitySet.name}", key${suffix}(id)))`
      )
    }
    lines.push(``)
  }

  return lines.join("\n")
}

/**
 * Generate the idToKey function for an entity type.
 */
const generateIdToKeyFunction = (
  entityType: EntityTypeModel,
  version: ODataVersion
): string => {
  const idTypeName = getIdTypeName(entityType.name)
  const isV4 = version === "V4"

  if (entityType.keys.length === 1) {
    const keyProp = entityType.keys[0]
    const keyTsType = keyProp.typeMapping.tsType

    // Check if key is a branded type that needs string conversion
    const isBrandedType = keyTsType.startsWith("BigDecimal.") ||
      keyTsType.startsWith("DateTime.") ||
      keyTsType.startsWith("Duration.")

    if (isBrandedType) {
      // Branded types are converted to string for EntityKey compatibility
      return `(id: ${idTypeName}) => typeof id === "string" ? { ${keyProp.odataName}: id } : { ${keyProp.odataName}: String(id.${keyProp.name}) }`
    }

    if (isV4) {
      // V4 can use number keys directly
      if (keyTsType === "number") {
        return `(id: ${idTypeName}) => typeof id === "number" ? id : id.${keyProp.name}`
      } else {
        return `(id: ${idTypeName}) => typeof id === "string" ? { ${keyProp.odataName}: id } : { ${keyProp.odataName}: id.${keyProp.name} }`
      }
    } else {
      // V2 supports both numeric and string keys
      if (keyTsType === "number") {
        return `(id: ${idTypeName}) => typeof id === "number" ? { ${keyProp.odataName}: id } : { ${keyProp.odataName}: id.${keyProp.name} }`
      } else {
        return `(id: ${idTypeName}) => typeof id === "string" ? { ${keyProp.odataName}: id } : { ${keyProp.odataName}: id.${keyProp.name} }`
      }
    }
  } else {
    // Composite key - convert branded types (BigDecimal, DateTime, Duration) to string
    const keyMapping = entityType.keys.map((k) => {
      const tsType = k.typeMapping.tsType
      // Branded types need to be converted to string for EntityKey compatibility
      if (tsType.startsWith("BigDecimal.") || tsType.startsWith("DateTime.") || tsType.startsWith("Duration.")) {
        return `${k.odataName}: String(id.${k.name})`
      }
      return `${k.odataName}: id.${k.name}`
    }).join(", ")
    return `(id: ${idTypeName}) => ({ ${keyMapping} })`
  }
}
